
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = 'C82D4000941CDFF7ED2F3718CD00C1AE'
    
_lr_action_items = {'STAR':([1,3,4,5,6,7,9,10,],[-1,6,-4,6,-6,6,-3,6,]),'SYMBOL':([0,1,2,3,4,5,6,7,8,9,10,],[1,-1,1,1,-4,1,-6,1,1,-3,-2,]),'RPARSEN':([1,2,4,5,6,7,9,10,],[-1,4,-4,9,-6,-5,-3,-2,]),'LPARSEN':([0,1,2,3,4,5,6,7,8,9,10,],[2,-1,2,2,-4,2,-6,2,2,-3,-2,]),'OR':([1,3,4,5,6,7,9,10,],[-1,8,-4,8,-6,8,-3,-2,]),'$end':([1,3,4,6,7,9,10,],[-1,0,-4,-6,-5,-3,-2,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,2,3,5,7,8,10,],[3,5,7,7,7,10,7,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> SYMBOL','expression',1,'p_expression_symbol','ply_enfa.py',51),
  ('expression -> expression OR expression','expression',3,'p_expression_or','ply_enfa.py',55),
  ('expression -> LPARSEN expression RPARSEN','expression',3,'p_expression_group','ply_enfa.py',60),
  ('expression -> LPARSEN RPARSEN','expression',2,'p_expression_epsilon','ply_enfa.py',64),
  ('expression -> expression expression','expression',2,'p_expression_concat','ply_enfa.py',72),
  ('expression -> expression STAR','expression',2,'p_expression_star','ply_enfa.py',76),
]
